/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_CapsuleCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_CapsuleCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_CapsuleCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
