/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_SphereCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_SphereCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_SphereCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
