/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeployAppInfo.java
 *
 * Created on Jan 8, 2010, 11:09:54 PM
 */

package g3dtools.deploy;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Kirill
 */
public class DeployAppInfo extends javax.swing.JDialog {

    private AppConfig config;
    private DeployLobby lobby;
    private JFileChooser chooser = new JFileChooser();
    private static final ImageFileFilter filter = new ImageFileFilter();

    private static class ImageFileFilter extends FileFilter {

        private String description;
        private String[] types;

        public ImageFileFilter(){
            types = ImageIO.getReaderFileSuffixes();
            description = "Image files (";
            for (int i = 0; i < types.length; i++){
                description += "*." + types[i];
                if (i != types.length - 1){
                    description += ", ";
                }
            }
            description += ")";
        }

        @Override
        public boolean accept(File f) {
            if (f.isDirectory())
                return true;

            String lcasename = f.getName().toLowerCase();
            for (String type : types){
                if (lcasename.endsWith("." + type))
                    return true;
            }
            return false;
        }
        @Override
        public String getDescription() {
            return description;
        }
    }

    /** Creates new form DeployAppInfo */
    public DeployAppInfo(DeployLobby lobby, AppConfig config) {
        super(lobby, "Application Info", true);
        this.config = config;
        this.lobby = lobby;

        initComponents();
        txtTitle.setText(config.getTitle());
        txtVendor.setText(config.getVendor());
        URL homepage = config.getHomepage();
        if (homepage != null)
            txtHomepage.setText(config.getHomepage().toString());
        txtLongDesc.setText(config.getDescription());
        txtDesc.setText(config.getShortDesc());
        
        BufferedImage image = config.getIcon();
        if (image != null){
            lblIconImg.setIcon(new ImageIcon(image));
        }

        setLocationRelativeTo(lobby);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblVendor = new javax.swing.JLabel();
        lblHomepage = new javax.swing.JLabel();
        lblShortDesc = new javax.swing.JLabel();
        lblLongDesc = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        sep = new javax.swing.JSeparator();
        txtTitle = new javax.swing.JTextField();
        txtVendor = new javax.swing.JTextField();
        txtHomepage = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        sclLongDesc = new javax.swing.JScrollPane();
        txtLongDesc = new javax.swing.JTextArea();
        lblIcon = new javax.swing.JLabel();
        lblIconImg = new javax.swing.JLabel();
        btnIconBrowse = new javax.swing.JButton();

        setTitle("Application Info");

        lblTitle.setText("Title: ");

        lblVendor.setText("Vendor: ");

        lblHomepage.setText("Homepage: ");

        lblShortDesc.setText("Short Description:");

        lblLongDesc.setText("Long Description");

        btnNext.setText("Next >");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtLongDesc.setColumns(20);
        txtLongDesc.setRows(3);
        sclLongDesc.setViewportView(txtLongDesc);

        lblIcon.setText("Icon: ");

        lblIconImg.setBackground(new java.awt.Color(0, 0, 0));

        btnIconBrowse.setText("Browse ...");
        btnIconBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconBrowseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, sclLongDesc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnNext)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, sep, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblShortDesc)
                            .add(lblHomepage)
                            .add(lblVendor)
                            .add(lblTitle)
                            .add(lblIcon))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(lblIconImg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(btnIconBrowse))
                            .add(txtTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .add(txtVendor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .add(txtHomepage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .add(txtDesc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                    .add(lblLongDesc))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblTitle)
                    .add(txtTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblVendor)
                    .add(txtVendor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblHomepage)
                    .add(txtHomepage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblShortDesc)
                    .add(txtDesc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblIcon)
                        .add(lblIconImg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnIconBrowse))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLongDesc)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sclLongDesc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(sep, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        ImageIcon imgIcon = (ImageIcon) lblIconImg.getIcon();
        if (imgIcon != null){
            BufferedImage image = (BufferedImage) imgIcon.getImage();
            config.setIcon(image);
        }
        
        config.setTitle(txtTitle.getText());
        config.setVendor(txtVendor.getText());
        try{
            config.setHomepage(new URL(txtHomepage.getText()));
        }catch (MalformedURLException ex){
            txtHomepage.setBackground(Color.RED);
            JOptionPane.showMessageDialog(this, "Please enter a URL in the homepage field",
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
        config.setDescription(txtLongDesc.getText());
        config.setShortDesc(txtDesc.getText());
        
        config.save();
        lobby.updateAppList();

        btnNext.setEnabled(false);
        DeployInputJars jars = new DeployInputJars(lobby, config);
        dispose();
        jars.setVisible(true);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnIconBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconBrowseActionPerformed
        chooser.setDialogTitle("Select icon image");
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File selected = chooser.getSelectedFile();
            if (selected.exists() && selected.isFile()){
                try{
                    BufferedImage image = ImageIO.read(selected);
                    if (image != null){
                        lblIconImg.setIcon(new ImageIcon(image));
                    }
                }catch (IOException ex){
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnIconBrowseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIconBrowse;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblHomepage;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIconImg;
    private javax.swing.JLabel lblLongDesc;
    private javax.swing.JLabel lblShortDesc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVendor;
    private javax.swing.JScrollPane sclLongDesc;
    private javax.swing.JSeparator sep;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtHomepage;
    private javax.swing.JTextArea txtLongDesc;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtVendor;
    // End of variables declaration//GEN-END:variables

}
