package g3dtools.deploy;

import javax.swing.DefaultComboBoxModel;

public class DeployAppSetting extends javax.swing.JDialog {

    private DeployLobby lobby;
    private AppConfig config;
    private DefaultComboBoxModel comboModel = new DefaultComboBoxModel();

    /** Creates new form DeployAppSetting */
    public DeployAppSetting(DeployLobby lobby, AppConfig config) {
        super(lobby, "Application Deployment Settings", true);

        this.lobby = lobby;
        this.config = config;

        // scan for applications
        AppFinderWorker worker = new AppFinderWorker(this, config);
        worker.execute();

        initComponents();
    }

    public void setAppList(String[] apps){
        for (String app : apps)
            comboModel.addElement(app);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblVer = new javax.swing.JLabel();
        lblJVer = new javax.swing.JLabel();
        cmbJVer = new javax.swing.JComboBox();
        txtVer = new javax.swing.JTextField();
        lblMainApp = new javax.swing.JLabel();
        cmbMainApp = new javax.swing.JComboBox();
        lblInitHeap = new javax.swing.JLabel();
        txtInitHeap = new javax.swing.JTextField();
        lblMaxHeap = new javax.swing.JLabel();
        txtMaxHeap = new javax.swing.JTextField();
        pnlWebstart = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        lblSubmenu = new javax.swing.JLabel();
        txtSubmenu = new javax.swing.JTextField();
        pnlApplet = new javax.swing.JPanel();
        lblWidth = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        txtWidth = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Application Settings");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("General Settings"));

        lblVer.setText("Version: ");

        lblJVer.setText("Java Version: ");

        cmbJVer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1.5+", "1.6+" }));

        lblMainApp.setText("Main Application: ");

        cmbMainApp.setModel(comboModel);

        lblInitHeap.setText("Initial heap size: ");

        lblMaxHeap.setText("Max heap size: ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblMainApp)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(cmbMainApp, 0, 289, Short.MAX_VALUE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblVer)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtVer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(lblJVer)
                        .add(10, 10, 10)
                        .add(cmbJVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblInitHeap)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtInitHeap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 133, Short.MAX_VALUE)
                        .add(lblMaxHeap)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtMaxHeap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblMainApp)
                    .add(cmbMainApp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblVer)
                    .add(txtVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(cmbJVer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblJVer))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblInitHeap)
                    .add(txtInitHeap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtMaxHeap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblMaxHeap))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlWebstart.setBorder(javax.swing.BorderFactory.createTitledBorder("Webstart Settings"));

        jCheckBox1.setText("Submenu shortcut");

        jCheckBox2.setText("Desktop shortcut");

        lblSubmenu.setText("Submenu name: ");
        lblSubmenu.setEnabled(false);

        txtSubmenu.setEnabled(false);

        org.jdesktop.layout.GroupLayout pnlWebstartLayout = new org.jdesktop.layout.GroupLayout(pnlWebstart);
        pnlWebstart.setLayout(pnlWebstartLayout);
        pnlWebstartLayout.setHorizontalGroup(
            pnlWebstartLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlWebstartLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlWebstartLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox2)
                    .add(pnlWebstartLayout.createSequentialGroup()
                        .add(21, 21, 21)
                        .add(lblSubmenu)
                        .add(14, 14, 14)
                        .add(txtSubmenu, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .add(jCheckBox1))
                .addContainerGap())
        );
        pnlWebstartLayout.setVerticalGroup(
            pnlWebstartLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlWebstartLayout.createSequentialGroup()
                .add(jCheckBox2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCheckBox1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlWebstartLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblSubmenu)
                    .add(txtSubmenu, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlApplet.setBorder(javax.swing.BorderFactory.createTitledBorder("Applet Settings"));

        lblWidth.setText("Width: ");

        lblHeight.setText("Height: ");

        txtWidth.setText("640");

        txtHeight.setText("480");
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlAppletLayout = new org.jdesktop.layout.GroupLayout(pnlApplet);
        pnlApplet.setLayout(pnlAppletLayout);
        pnlAppletLayout.setHorizontalGroup(
            pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAppletLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblWidth)
                    .add(lblHeight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtWidth)
                    .add(txtHeight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        pnlAppletLayout.setVerticalGroup(
            pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAppletLayout.createSequentialGroup()
                .add(pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblWidth)
                    .add(txtWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAppletLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblHeight)
                    .add(txtHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNext.setText("Next >");

        btnPrev.setText("< Prev");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlApplet, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnlWebstart, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnPrev)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnNext)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlWebstart, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlApplet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnNext)
                    .add(btnPrev))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JComboBox cmbJVer;
    private javax.swing.JComboBox cmbMainApp;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblInitHeap;
    private javax.swing.JLabel lblJVer;
    private javax.swing.JLabel lblMainApp;
    private javax.swing.JLabel lblMaxHeap;
    private javax.swing.JLabel lblSubmenu;
    private javax.swing.JLabel lblVer;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JPanel pnlApplet;
    private javax.swing.JPanel pnlWebstart;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtInitHeap;
    private javax.swing.JTextField txtMaxHeap;
    private javax.swing.JTextField txtSubmenu;
    private javax.swing.JTextField txtVer;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables

}
