/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestJava2D.java
 *
 * Created on 08.04.2010, 01:07:29
 */

package com.jme3.gde.gui.renderer;

import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.sound.SoundSystem;
import de.lessvoid.nifty.tools.TimeProvider;

/**
 *
 * @author normenhansen
 */
public class TestJava2D extends javax.swing.JFrame {
    Nifty nifty;
    Java2dRenderDevice dev=new Java2dRenderDevice();

    /** Creates new form TestJava2D */
    public TestJava2D() {
        initComponents();
        setSize(1024,768);

        jPanel1.add(dev);
        nifty = new Nifty(dev,
                    new SoundSystem(new Java2dSoundDevice()),
                    dev.getInputSystem(),
                    new TimeProvider());
        nifty.fromXml("tutorial/tutorial.xml","start");
        new Thread(run).start();
    }

    private boolean running=true;
    private Runnable run=new Runnable() {
        public void run() {
            running=true;
            while(running){
                if(nifty.render(true)){
                    running=false;
                }
//                dev.repaint();
//                java.awt.EventQueue.invokeLater(repaint);
            }
        }
    };

    private Runnable repaint=new Runnable() {
        public void run() {
            dev.repaint();
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestJava2D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
